name: Databricks CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  databricks-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Validate Python Files
        run: |
          echo "Running code quality checks..."
          pip install flake8 pytest
          flake8 notebooks/ --ignore=E501
          pytest tests/

      - name: Trigger Databricks Job (Optional)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Triggering Databricks job run..."
          databricks jobs run-now --job-id ${{ secrets.DATABRICKS_JOB_ID }}

